pipeline{
    agent any

    stages{
        // Add the "Deploy" stage here
	stage('Deploy') {
	   steps {
             sh '''
                 oc project avissg-deploy-strategies
                 oc start-build greeting-service --follow --wait
             '''
           }
        }
    }
}
