pipeline{
    agent any

    stages{
        stage("Install dependencies"){
            steps{
                sh "npm ci"
            }
        }

        stage("Check Style"){
            steps{
                sh "npm run lint"
            }
        }

        stage("Test"){
            steps{
                sh "npm test"
            }
        }

        // Add the "Deploy" stage here
	stage('Deploy') {
	   steps {
             sh '''
                 oc project avissg-deploy-strategies
                 oc start-build greeting-service --follow --wait
             '''
           }
        }
    }
}
